---
- name: A lab about lists
  hosts: slave1
  vars_files:
    - vars/users-list
  tasks:
    - name: print list values
      debug:
        msg: "User {{ item.username}} has homedirectory {{ item.homedir }} and shell {{ item.shell}}"
      loop: "{{ users}}"
    - name: print the third index in the array
      debug:
        msg: "the third item is {{ users[2] }}"
