---
- name: Installation stage
  hosts: all
  tasks:
    - name: Installing vsftpd
      yum:
        name: vsftpd
        state: installed
    - name: starting vsftpd
      service:
        name: vsftpd
        state: started
        enbaled: yes
    - name: open firewalld
      firewalld:
        service: ftp
        state: enabled
        permanent: yes
        immediate: yes

- name: vsftpd configuration using templae
  hosts: all
  vars:
    - anonymous_enable: yes
    - local_enable: yes
    - write_enable: yes
    - anon_upload_enable: yes
  tasks:
    - name: Copy template
      template:
        src: vsftpd_conf.j2
        dest: /etc/vsftpd/vsftpd.conf
 
- name: configure the selinux perms 
  hosts: all
  tasks:
    - name: Installing dependencies
      yum:
        name: policycoreutils-python-utils
        state: present
    - name: setting permissiong
      file:
        path: /var/ftp/pub
        mode: '0777'
    - name: setting seboolean
      seboolean:
        name: ftpd_anon_write
        state: yes
        presistent: yes
    - name: setting the file context label
      sefcontext:
        target: /var/ftp/pub
        setype: public_content_rw_t
        present: yes
      notify:
        - apply_changes
  handlers:
    - name: apply_changes
      command: restorecon -v /var/ftp/pub

- name: verify
  hosts: localhost
  tasks:
    - name: install lftp
      yum:
        name: lftp
        state: present
    - name: upload a file
      shell: >
        lftp slave1 <<EOF
        cd pub
        put /etc/hosts
        EOF
