---
- name: demo failed_when
  hosts: all
  tasks:
    - name: print Hello World
      command: echo Hello World
      ignore_errors: yes
      register: result
      failed_when: "'World' in result.stdout"
    - name: are we here yet?
      debug:
        msg: hello
