---
- name: install and start the web service
  hosts: slave1
  tasks:
  - name: install the package
    yum:
      name: "{{ ansible_facts['ansible_local']['packages']
['software']['package'] }}"
      state: latest
  - name: start the service
    service:
      name: "{{ ansible_facts['ansible_local']['packages']
['software']['service'] }}"
      state: "{{ ansible_facts['ansible_local']['packages']
['software']['state'] }}"
      enabled: "{{ ansible_facts['ansible_local']['packages']
['software']['enabled'] }}"
