---
- name: configure sudo
  hosts: slave1, slave2
  vars_files:
    - vars/defaults
    - vars/users.yml
    - vars/groups.yml
  tasks:
    - name: add groups
      group:
        name: "{{ item.groupname }}"
      loop: "{{ groupname }}"
    - name: add users
      user:
        name: "{{ item.username }}"
        groups: "{{ item.groups }}"
      loop: "{{ users }}"
    - name: add authorized keys
      authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file', 'files/' + item.username + '/id_rsa.pub') }}"
      loop: "{{ users }}"

    - name: allow group memebers in sudo
      template:
        src: sudoers.j2
        dest: /etc/sudoers.d/sudogroups
        validate: visudo -cf %s 
        mode: 0440
